version: '3.4'
services:
  nginx:
    build: ../nginx
    ports:
      - "80:80"
    depends_on:
      - backend-1
      - backend-2
  backend-1:
    build:
      context: .
    container_name: backend-1
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
            "server.port" : "8081"
          }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  backend-2:
    build:
      context: .
    container_name: backend-2
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
              "server.port" : "8082"
            }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true